### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by lover202** [VirtualDisgrace/opencollar#1079] opened 2018-03-12 20:29 UTC
you revoked 2 lsl scripts . read gpl again... dumb... you cant revoke it...  once its gpl'ed ... too bad...

**Comment by minakitty** [comment] 2018-03-12 20:37
Your issue may be made more useful by mentioning exactly what scripts have been revoked, and what you mean by them being revoked.  As it is right now, your post gives no useful information for reproducing or troubleshooting an error

**Comment by WendyStarfall** [comment] 2018-03-12 20:58
@lover202 

The General Public License, version 2 is revokable.

Licensing under the GPL, v2 doesn't imply waiving the copyright of ones originally authored source code.

Feel free to consult your attorney of choice for clarification.

@minakitty

I assume that this is referring to the ``oc_remote_leashpost.lsl`` and ``.aoloader.lsl``, which both are original source code by either @GarvinTwine alone, or co-authored by me and @GarvinTwine together.

These programs were forked by another party, and then claims were made by this party that they were the official distributing entity of this source code, while we are being defamed, also by this same party, in documents that are linked in some Second Life® groups.

These kind of jabs and worse harassment are going on since November last year. Someone opened a forum topic at SLU about it: http://www.sluniverse.com/php/vb/general-sl-discussion/130906-hostile-takeover-opencollar-group.html

My own statement about all this can be found at www.opencollar.at/blog

**Comment by GarvinTwine** [comment] 2018-03-13 00:36
@lover202 and how does this issue relate to anything concerning this repo?
Making a new github account for trolling... yeah you really get the idea of github, open source and GPL.
But this shows just once more how some people just try to defame and troll us,  thanks for the proof here.
Closing this issues due to not relevant to anything.

**Closed by GarvinTwine** 2018-03-13 00:36 UTC

**Comment by minakitty** [comment] 2018-03-13 03:54
@WendyStarfall Thanks.  My gut was telling me it was related to that fork, but I wanted to give the benefit of the doubt and try to be helpful.  Guess this issue can be closed?
